### ISSUE TITLE
端口跳跃优化建议

### ISSUE THREAD

**Issue by mingxiaoyu** [muink/openwrt-fchomo#6]
如下图。。 假如我的端口跳跃是20000-40000
这个搞法是不是可以优化下？
官方是可以这样的：  ports: 20000-40000
<img width="328" alt="image" src="https://github.com/user-attachments/assets/4f69759d-32dc-45dd-8b56-fef49d7da5b8">

**Comment by muink** [comment]
![image](https://github.com/user-attachments/assets/1304f8e3-8352-4f6a-a32b-37210d200ad7)
实际上是支持这样的写法的
