### ISSUE TITLE
能不能出一期fchomo教程，我在第一步添加订阅都不知道怎么设置了，在网上搜索相关教程都没找到

### ISSUE THREAD

**Issue by wherss1** [muink/openwrt-fchomo#9]

**Comment by muink** [comment]
本项目功能与 [mihomo 文档](https://wiki.metacubex.one/config/)保持一致, 文档怎么设置这里就怎么设置
此外本项目在设计逻辑上比较接近 homeproxy, 您可以参考下 homeproxy 的教程视频
配置一个客户端需要至少配置 `全局` `客户端` `节点` 这几个大标签
订阅在 `节点` -> `供应商` 中设置

**Comment by 1123123w** [comment]
这东西就不是人类用的，kwrt更新了一下变成了这玩意，还是原来的mihomo tproxy好用

**Comment by 1123123w** [comment]
搞笑的反人类，这个供应商的输入框，不是给你填订阅链接，是给你输入名称，按添加后，再确认具体配置。不会设计ui，就去学一学
